import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import LatexComponent from "./latex/component/LatexComponent";
import { useState } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const [latex, setLatex] = useState<string>(''); // Store raw user input here

  const handleTextareaChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    const rawValue = event.target.value;
    setLatex(rawValue); // Update raw input state
  };

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <textarea
        value={latex} // Bind textarea value to state
        onChange={handleTextareaChange} // Update state on textarea change
        rows={10}
        cols={50}
        placeholder="Enter your LaTeX code here with delimiters"
      />

      <h2>Rendered Output:</h2>
        <LatexComponent expression={latex} />
      </div>
    </>
  );
}
